### ISSUE TITLE
bug: 修复 gh-action 文件错误

### ISSUE THREAD

**Issue by whg517** [pyloong/cookiecutter-pythonic-project#23]
### 原因：

gh-action 中 使用 `matrix` 策略没有正确配置 python 版本，导致在执行 test 时，使用 os 的默认版本 python 3.8

### 修复：

- 为 test 的 python action 增加引用版本
- 为 lint 的 python action 增加引用版本

相关资料： [Using a matrix for your jobs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) ，[actions/setup-python](https://github.com/actions/setup-python)

### 示例

```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
```
