### ISSUE TITLE
生成项目的 gitflow 错误

### ISSUE THREAD

**Issue by whg517** [pyloong/cookiecutter-pythonic-project#4]
在生成项目时，选择使用 `github` 的 CI 时，生成的 gitflows 文件有错误存在。

### 异常信息

`The workflow is not valid. Job deploy depends on unknown job build.`

### 原因

gitflow 中的 `deploy` 任务依赖的的 `build` 任务不存在。

https://github.com/pyloong/cookiecutter-pythonic-project/blob/75c1e0b1f22b1b35678cd7e2731141672d80137b/%7B%7B%20cookiecutter.project_slug%20%7D%7D/.github/workflows/main.yml#L55-L60

### 解决

`deploy` 任务依赖 `test` 任务和 `lint` 任务

```yaml
  deploy:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'file2mongo'

    runs-on: ubuntu-latest

    needs:
      - test
      - linting
```
